<h1 style="text-align: center;">NumPy Fundamentals</h1>

### Install NumPy

In [1]:
!pip install numpy

### Import NumPy

In [2]:
import numpy as np

### Creating NumPy Arrays

In [3]:
# 1 Dimensional or Vector
arr = np.array([1, 2, 3])

print(f"Type: {type(arr)}\nArray: {arr}")

Type: <class 'numpy.ndarray'>
Array: [1 2 3]


In [4]:
# 2 Dimensional or Matrix
arr = np.array(
    [
        [1, 2, 3],
        [4, 5, 6],
    ]
)

print(arr)

[[1 2 3]
 [4 5 6]]


In [5]:
# 3 Dimensional or Tensor
arr = np.array(
    [
        [[1, 2], [3, 4]],
        [[5, 6], [7, 8]],
    ]
)

print(arr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [6]:
# checking the data types of various NumPy arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([1., 2., 3.])
arr3 = np.array(['a', 'b', 'c'])
arr4 = np.array([True, False, True])
arr5 = np.array([1.0 + 2.0j, 2.5 + 3.5j])

print(f"""
    Array 01 Data Type: {arr1.dtype},
    Array 02 Data Type: {arr2.dtype},
    Array 03 Data Type: {arr3.dtype},
    Array 04 Data Type: {arr4.dtype},
    Array 05 Data Type: {arr5.dtype},
""")


    Array 01 Data Type: int32,
    Array 02 Data Type: float64,
    Array 03 Data Type: <U1,
    Array 04 Data Type: bool,
    Array 05 Data Type: complex128,



In [7]:
# converting int to float
np.array([1, 2, 3], dtype=float)

array([1., 2., 3.])

In [8]:
# converting int to bool
np.array([0, 2, 3], dtype=bool)

array([False,  True,  True])

In [9]:
# converting int to complex
np.array([1, 2, 3], dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [10]:
# converting int32 to int64
arr = np.array([1, 2, 3], dtype=np.int32)
arr = arr.astype(np.int64)

arr.dtype

dtype('int64')

In [11]:
# arange is similar to the range function in python
arr1 = np.arange(1, 11)
arr2 = np.arange(1, 11, 2)

print(f"Arange Array 01: {arr1}")
print(f"Arange Array 02: {arr2}")

Arange Array 01: [ 1  2  3  4  5  6  7  8  9 10]
Arange Array 02: [1 3 5 7 9]


In [12]:
# reshape changes the dimensions of a array
arr = np.arange(1, 11)

arr.reshape(2, 5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [13]:
# generating NumPy arrays filled with ones
arr1 = np.ones((1, ))
arr2 = np.ones((3, 2))

print(f"Array 01: {arr1}")
print(f"Array 02: \n{arr2}")

Array 01: [1.]
Array 02: 
[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [14]:
# generating NumPy arrays filled with zeros
arr1 = np.zeros((1, ))
arr2 = np.zeros((3, 2))

print(f"Array 01: {arr1}")
print(f"Array 02: \n{arr2}")

Array 01: [0.]
Array 02: 
[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [15]:
# generating NumPy arrays filled with random values
arr1 = np.random.random((1, ))
arr2 = np.random.random((3, 2))

print(f"Random Array 01: {arr1}")
print(f"Random Array 02: \n{arr2}")

Random Array 01: [0.76256092]
Random Array 02: 
[[0.92591983 0.26965188]
 [0.71694234 0.36623858]
 [0.13318047 0.40534737]]


In [16]:
# linear space
# np.linspace(lower_range, upper_range, size)
np.linspace(-10, 10, 5)

array([-10.,  -5.,   0.,   5.,  10.])

In [17]:
# generating the identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])